var schedule = [
  {
    id: 21424,
    name: 'Занятие 31',
    room: { id: 7, name: 'Сикорский', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-05T17:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3130-6235-4738-b430-393963393531/3.jpg',
    description: '',
    baseLesson: {
      id: 1084,
      name: 'Инженеры-изобретатели',
      duration: 90,
      directionId: 7,
      status: 1,
      minClass: 1,
      maxClass: 2,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Ситдикова Камилла'],
    teacher: { name: 'Ситдикова Камилла', bio: '', avatar: '' }
  },
  {
    id: 21460,
    name: 'Занятие 31',
    room: { id: 8, name: 'Леонардо', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-05T17:00:00+03:00',
    direction: 'Развитие способностей',
    cover:
      'https://static.tildacdn.com/tild3562-3466-4636-a132-623131396338/1.jpg',
    description: '',
    baseLesson: {
      id: 1085,
      name: 'Шахматы(продолжающие)',
      duration: 60,
      directionId: 8,
      status: 1,
      minClass: null,
      maxClass: null,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Кушнерев Олег'],
    teacher: { name: 'Кушнерев Олег', bio: '', avatar: '' }
  },
  {
    id: 21388,
    name: 'Занятие 31',
    room: { id: 5, name: 'Азимов', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-05T18:00:00+03:00',
    direction: 'Электроника',
    cover:
      'https://static.tildacdn.com/tild6135-3839-4136-b230-373030623233/72b2aadd3592408ea6ac5b4b6acc52a0.png',
    description: '',
    baseLesson: {
      id: 1083,
      name: 'Электроника (продолжение)',
      duration: 90,
      directionId: 13,
      status: 1,
      minClass: 5,
      maxClass: 7,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Рудов Дмитрий '],
    teacher: { name: 'Рудов Дмитрий ', bio: '', avatar: '' }
  },
  {
    id: 21496,
    name: 'Занятие 31',
    room: { id: 8, name: 'Леонардо', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-05T18:00:00+03:00',
    direction: 'Развитие способностей',
    cover:
      'https://static.tildacdn.com/tild3562-3466-4636-a132-623131396338/1.jpg',
    description: '',
    baseLesson: {
      id: 1086,
      name: 'Шахматы(продвинутые)',
      duration: 90,
      directionId: 8,
      status: 1,
      minClass: null,
      maxClass: null,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Кушнерев Олег'],
    teacher: { name: 'Кушнерев Олег', bio: '', avatar: '' }
  },
  {
    id: 25912,
    name: 'Занятие 21',
    room: { id: 6, name: 'Чебышев', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T10:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3238-3863-4934-a239-616563613337/d1e19ed57b2b469fa0bcc4b87562cd8d.png',
    description: 'Базовые занятия по 3D моделированию и печати',
    baseLesson: {
      id: 1293,
      name: '3D-графика в TinckerCAD ',
      duration: 90,
      directionId: 7,
      status: 1,
      minClass: 1,
      maxClass: 4,
      minAge: 7,
      maxAge: 11
    },
    teachersName: ['Погребняк Надежда '],
    teacher: { name: 'Погребняк Надежда ', bio: '', avatar: '' }
  },
  {
    id: 25936,
    name: 'Занятие 29',
    room: { id: 7, name: 'Сикорский', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T10:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3034-6134-4338-a633-356435386430/3b2262bff6304142aa101f9118f70852.jpg',
    description: '',
    baseLesson: {
      id: 1094,
      name: 'Авиамоделирование (начало)',
      duration: 120,
      directionId: 7,
      status: 1,
      minClass: 3,
      maxClass: 4,
      minAge: 8,
      maxAge: 11
    },
    teachersName: [' Фёдоров Александр'],
    teacher: { name: ' Фёдоров Александр', bio: '', avatar: '' }
  },
  {
    id: 26449,
    name: 'Занятие 13',
    room: { id: 13, name: 'Столярная мастерская', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Запись закрыта',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T10:00:00+03:00',
    direction: null,
    cover: null,
    description: null,
    baseLesson: {
      id: 1496,
      name: 'Моды Minecraft 2019',
      duration: 90,
      directionId: null,
      status: 2,
      minClass: 1,
      maxClass: 4,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Сербаев Даниил '],
    teacher: { name: 'Сербаев Даниил ', bio: '', avatar: '' }
  },
  {
    id: 21640,
    name: 'Занятие 31',
    room: { id: 5, name: 'Азимов', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T10:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3130-6235-4738-b430-393963393531/3.jpg',
    description: '',
    baseLesson: {
      id: 1090,
      name: 'Инженеры-изобретатели (Начало)',
      duration: 120,
      directionId: 7,
      status: 1,
      minClass: 3,
      maxClass: 4,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Стегура Никита'],
    teacher: { name: 'Стегура Никита', bio: '', avatar: '' }
  },
  {
    id: 25874,
    name: 'Занятие 13',
    room: { id: 13, name: 'Столярная мастерская', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T12:00:00+03:00',
    direction: 'Чанк Программирование',
    cover: '',
    description: '',
    baseLesson: {
      id: 1486,
      name: 'Scratch программирование 2019',
      duration: 90,
      directionId: 15,
      status: 1,
      minClass: 3,
      maxClass: 4,
      minAge: 9,
      maxAge: 11
    },
    teachersName: ['Погребняк Надежда '],
    teacher: { name: 'Погребняк Надежда ', bio: '', avatar: '' }
  },
  {
    id: 21532,
    name: 'Занятие 8',
    room: { id: 4, name: 'Паскаль', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T12:00:00+03:00',
    direction: 'Виртуальной реальности',
    cover:
      'https://static.tildacdn.com/tild3930-3133-4566-a332-306263303462/IMG_6000.jpg',
    description: '',
    baseLesson: {
      id: 1087,
      name: '3D игры: Blender и Unity (Продолжение)',
      duration: 90,
      directionId: 10,
      status: 1,
      minClass: 5,
      maxClass: 11,
      minAge: 12,
      maxAge: 18
    },
    teachersName: ['Сербаев Даниил '],
    teacher: { name: 'Сербаев Даниил ', bio: '', avatar: '' }
  },
  {
    id: 21820,
    name: 'Занятие 31',
    room: { id: 7, name: 'Сикорский', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T12:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3130-6235-4738-b430-393963393531/3.jpg',
    description: '',
    baseLesson: {
      id: 1095,
      name: 'Инженеры-изобретатели ',
      duration: 90,
      directionId: 7,
      status: 1,
      minClass: 1,
      maxClass: 2,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Зайцев Антон '],
    teacher: { name: 'Зайцев Антон ', bio: '', avatar: '' }
  },
  {
    id: 21676,
    name: 'Занятие 31',
    room: { id: 5, name: 'Азимов', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Запись закрыта',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T12:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3130-6235-4738-b430-393963393531/3.jpg',
    description: '',
    baseLesson: {
      id: 1091,
      name: 'Инженеры-изобретатели (Начало)',
      duration: 120,
      directionId: 7,
      status: 2,
      minClass: 5,
      maxClass: 10,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Рудов Дмитрий '],
    teacher: { name: 'Рудов Дмитрий ', bio: '', avatar: '' }
  },
  {
    id: 28448,
    name: 'Занятие 1',
    room: { id: 6, name: 'Чебышев', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 1,
    textType: 'Мастер-класс',
    startDate: '2019-04-06T14:00:00+03:00',
    direction: 'Мастер-класс',
    cover:
      'https://static.tildacdn.com/tild6438-6263-4264-b861-373436333035/3e0e3262-3598-4c42-9.jpg',
    description:
      'Орудия древности, бравшие города и замки, вернулись в Геккон-клуб, чтобы показать, на что были способны древние инженеры. На мастер-классе дети узнают об истории катапульт, инженерных принципах, стоящих за их работой и о том, почему катапульты — совсем не то, чем кажутся. В завершении мастер-класса ребята соберут настоящую карманную катапульту и заберут ее себе домой!',
    baseLesson: {
      id: 1859,
      name: 'МК Катапульта 06.04',
      duration: 60,
      directionId: 17,
      status: 1,
      minClass: 1,
      maxClass: 3,
      minAge: 6,
      maxAge: 10
    },
    teachersName: ['Ильина Екатерина'],
    teacher: { name: 'Ильина Екатерина', bio: '', avatar: '' }
  },
  {
    id: 28202,
    name: 'Занятие 17',
    room: { id: 8, name: 'Леонардо', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T14:00:00+03:00',
    direction: 'Физико-математический Чанк',
    cover:
      'https://static.tildacdn.com/tild6164-6237-4531-b839-333237376135/5.jpg',
    description: '',
    baseLesson: {
      id: 1318,
      name: 'Математика 2х2 ',
      duration: 90,
      directionId: 9,
      status: 1,
      minClass: 3,
      maxClass: 3,
      minAge: 8,
      maxAge: 10
    },
    teachersName: ['Изотова Анастасия'],
    teacher: { name: 'Изотова Анастасия', bio: '', avatar: '' }
  },
  {
    id: 21568,
    name: 'Занятие 8',
    room: { id: 4, name: 'Паскаль', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Запись закрыта',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T14:00:00+03:00',
    direction: 'Виртуальной реальности',
    cover:
      'https://static.tildacdn.com/tild3930-3133-4566-a332-306263303462/IMG_6000.jpg',
    description: '',
    baseLesson: {
      id: 1088,
      name: 'Моды майнкрафта',
      duration: 90,
      directionId: 10,
      status: 2,
      minClass: 1,
      maxClass: 4,
      minAge: 7,
      maxAge: 12
    },
    teachersName: ['Сербаев Даниил '],
    teacher: { name: 'Сербаев Даниил ', bio: '', avatar: '' }
  },
  {
    id: 26489,
    name: 'Занятие 13',
    room: { id: 13, name: 'Столярная мастерская', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T14:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3130-6235-4738-b430-393963393531/3.jpg',
    description: '',
    baseLesson: {
      id: 1498,
      name: 'Инженеры-изобретатели 2019',
      duration: 90,
      directionId: 7,
      status: 1,
      minClass: 1,
      maxClass: 2,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Стегура Никита'],
    teacher: { name: 'Стегура Никита', bio: '', avatar: '' }
  },
  {
    id: 25981,
    name: 'Занятие 25',
    room: { id: 6, name: 'Чебышев', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T14:00:00+03:00',
    direction: 'Виртуальной реальности',
    cover: null,
    description: null,
    baseLesson: {
      id: 1280,
      name: '3D-графика и печать 2019',
      duration: 90,
      directionId: 10,
      status: 1,
      minClass: 3,
      maxClass: 4,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Погребняк Надежда '],
    teacher: { name: 'Погребняк Надежда ', bio: '', avatar: '' }
  },
  {
    id: 22036,
    name: 'Занятие 31',
    room: { id: 8, name: 'Леонардо', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T16:00:00+03:00',
    direction: 'Физико-математический Чанк',
    cover:
      'https://static.tildacdn.com/tild6164-6237-4531-b839-333237376135/5.jpg',
    description: '',
    baseLesson: {
      id: 1101,
      name: 'Математика 2х2 ',
      duration: 60,
      directionId: 9,
      status: 1,
      minClass: 2,
      maxClass: 2,
      minAge: 6,
      maxAge: 8
    },
    teachersName: [' Салахетдинов Руслан'],
    teacher: { name: ' Салахетдинов Руслан', bio: '', avatar: '' }
  },
  {
    id: 28447,
    name: 'Занятие 1',
    room: { id: 6, name: 'Чебышев', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 1,
    textType: 'Мастер-класс',
    startDate: '2019-04-06T16:00:00+03:00',
    direction: 'Мастер-класс',
    cover:
      'https://static.tildacdn.com/tild3961-3831-4331-a366-393564383736/__2017-12-05__160515.png',
    description:
      'В основе конструкции — робот, которого дети собирают из деталей, изготовленных лазером. В его голове — светодиоды, благодаря чему он светится.\r\n\r\nРебята на мастер классе:\r\nпознакомятся с азами электроники\r\nнаучаться работать с паяльником и другими инструментами\r\nузнают, что такое светодиод и резистор\r\nРебята самостоятельно соберут настоящую роболампу, которую можно использовать как лампу на рабочем столе или же как ночник. \r\nЗаписаться на мастер-класс ',
    baseLesson: {
      id: 1858,
      name: 'МК Роболампа 06.04',
      duration: 60,
      directionId: 17,
      status: 1,
      minClass: 1,
      maxClass: 10,
      minAge: 7,
      maxAge: 17
    },
    teachersName: ['Бувина Юлия'],
    teacher: { name: 'Бувина Юлия', bio: '', avatar: '' }
  },
  {
    id: 21604,
    name: 'Занятие 8',
    room: { id: 4, name: 'Паскаль', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T16:00:00+03:00',
    direction: 'Виртуальной реальности',
    cover:
      'https://static.tildacdn.com/tild3930-3133-4566-a332-306263303462/IMG_6000.jpg',
    description: '',
    baseLesson: {
      id: 1089,
      name: '3d-моделирование для игр Unity',
      duration: 90,
      directionId: 10,
      status: 1,
      minClass: 5,
      maxClass: 10,
      minAge: 12,
      maxAge: 18
    },
    teachersName: ['Сербаев Даниил '],
    teacher: { name: 'Сербаев Даниил ', bio: '', avatar: '' }
  },
  {
    id: 26006,
    name: 'Занятие 29',
    room: { id: 7, name: 'Сикорский', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T16:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3034-6134-4338-a633-356435386430/3b2262bff6304142aa101f9118f70852.jpg',
    description: '',
    baseLesson: {
      id: 1097,
      name: 'Авиамоделирование (продолжение)',
      duration: 120,
      directionId: 7,
      status: 1,
      minClass: 2,
      maxClass: 3,
      minAge: null,
      maxAge: null
    },
    teachersName: [' Фёдоров Александр'],
    teacher: { name: ' Фёдоров Александр', bio: '', avatar: '' }
  },
  {
    id: 21928,
    name: 'Занятие 31',
    room: { id: 6, name: 'Чебышев', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T16:00:00+03:00',
    direction: 'Развитие способностей',
    cover:
      'https://static.tildacdn.com/tild3562-3466-4636-a132-623131396338/1.jpg',
    description: '',
    baseLesson: {
      id: 1098,
      name: 'Шахматы (начинающие)',
      duration: 60,
      directionId: 8,
      status: 1,
      minClass: null,
      maxClass: null,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Кушнерев Олег'],
    teacher: { name: 'Кушнерев Олег', bio: '', avatar: '' }
  },
  {
    id: 21964,
    name: 'Занятие 31',
    room: { id: 6, name: 'Чебышев', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T16:00:00+03:00',
    direction: 'Развитие способностей',
    cover:
      'https://static.tildacdn.com/tild3562-3466-4636-a132-623131396338/1.jpg',
    description: '',
    baseLesson: {
      id: 1099,
      name: 'Шахматы (продолжающие)',
      duration: 60,
      directionId: 8,
      status: 1,
      minClass: null,
      maxClass: null,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Кушнерев Олег'],
    teacher: { name: 'Кушнерев Олег', bio: '', avatar: '' }
  },
  {
    id: 27854,
    name: 'Занятие 47',
    room: { id: 19, name: 'Школа Программирования ', affiliate_id: 8 },
    branch: 'Геккон-Октябрьская',
    textStatus: 'Запись закрыта',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T16:00:00+03:00',
    direction: 'Школа программирования',
    cover: null,
    description: null,
    baseLesson: {
      id: 1299,
      name: 'Октябрьская. Информационная безопасность',
      duration: 120,
      directionId: 16,
      status: 2,
      minClass: 7,
      maxClass: 11,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Никита Гнилозуб-Волобуев'],
    teacher: { name: 'Никита Гнилозуб-Волобуев', bio: '', avatar: '' }
  },
  {
    id: 27642,
    name: 'Занятие 17',
    room: { id: 19, name: 'Школа Программирования ', affiliate_id: 8 },
    branch: 'Геккон-Октябрьская',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T16:00:00+03:00',
    direction: 'Школа программирования',
    cover: null,
    description: null,
    baseLesson: {
      id: 1705,
      name: 'Питон для продолжающих 2019/1',
      duration: 90,
      directionId: 16,
      status: 1,
      minClass: 7,
      maxClass: 11,
      minAge: null,
      maxAge: null
    },
    teachersName: [' Ростислав Бородин'],
    teacher: {
      name: ' Ростислав Бородин',
      bio: '',
      avatar: 'http://class.roctbb.net'
    }
  },
  {
    id: 28468,
    name: 'Занятие 1',
    room: { id: 6, name: 'Чебышев', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 1,
    textType: 'Мастер-класс',
    startDate: '2019-04-06T17:00:00+03:00',
    direction: 'Мастер-класс',
    cover:
      'https://static.tildacdn.com/tild3938-6533-4763-a363-343634613537/IMG_1206_-_.JPG',
    description:
      'На мастер-классе ребята соберут летящего дракона. работающего на конструкции с шестеренками. С помощью  возвратно-поступательного механизма они смогут отправить его в полет.\r\nНа мастер-классе ребята узнают, что такое пониженная зубчатая передача, о превращении вращательного движения в возвратно-поступательное, также они научатся работать с ручным инструментом.\r\n',
    baseLesson: {
      id: 1873,
      name: 'МК Приручи дракона 06.04',
      duration: 60,
      directionId: 17,
      status: 1,
      minClass: 1,
      maxClass: 4,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Бувина Юлия'],
    teacher: { name: 'Бувина Юлия', bio: '', avatar: '' }
  },
  {
    id: 26035,
    name: 'Занятие 30',
    room: { id: 8, name: 'Леонардо', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T17:00:00+03:00',
    direction: 'Физико-математический Чанк',
    cover:
      'https://static.tildacdn.com/tild6164-6237-4531-b839-333237376135/5.jpg',
    description: '',
    baseLesson: {
      id: 1223,
      name: 'Математика 2х2 ',
      duration: 60,
      directionId: 9,
      status: 1,
      minClass: 0,
      maxClass: 1,
      minAge: 6,
      maxAge: 7
    },
    teachersName: [' Салахетдинов Руслан'],
    teacher: { name: ' Салахетдинов Руслан', bio: '', avatar: '' }
  },
  {
    id: 28348,
    name: 'Занятие 5',
    room: { id: 5, name: 'Азимов', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T17:00:00+03:00',
    direction: null,
    cover: null,
    description: null,
    baseLesson: {
      id: 1821,
      name:
        'Индивидуальное по пилотированию коптеров 16.03 ( 17:00) - 17.03 ( 18:15) - ( и еще на три занятия поставить даты по договоренности)',
      duration: null,
      directionId: null,
      status: 1,
      minClass: null,
      maxClass: null,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Оборин Федор'],
    teacher: { name: 'Оборин Федор', bio: '', avatar: '' }
  },
  {
    id: 26759,
    name: 'Занятие 13',
    room: { id: 7, name: 'Сикорский', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T18:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3130-6235-4738-b430-393963393531/3.jpg',
    description: '',
    baseLesson: {
      id: 1538,
      name: 'Инженеры-изобретатели 2019',
      duration: 120,
      directionId: 7,
      status: 1,
      minClass: 5,
      maxClass: 10,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Рудов Дмитрий '],
    teacher: { name: 'Рудов Дмитрий ', bio: '', avatar: '' }
  },
  {
    id: 28329,
    name: 'Занятие 6',
    room: { id: 19, name: 'Школа Программирования ', affiliate_id: 8 },
    branch: 'Геккон-Октябрьская',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T18:00:00+03:00',
    direction: 'Школа программирования',
    cover: null,
    description: null,
    baseLesson: {
      id: 1714,
      name: 'Питон для начинающих - онлайн группа',
      duration: null,
      directionId: 16,
      status: 1,
      minClass: 7,
      maxClass: 11,
      minAge: null,
      maxAge: null
    },
    teachersName: [' Ростислав Бородин'],
    teacher: {
      name: ' Ростислав Бородин',
      bio: '',
      avatar: 'http://class.roctbb.net'
    }
  },
  {
    id: 26055,
    name: 'Занятие 28',
    room: { id: 8, name: 'Леонардо', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T18:00:00+03:00',
    direction: 'Физико-математический Чанк',
    cover:
      'https://static.tildacdn.com/tild6164-6237-4531-b839-333237376135/5.jpg',
    description: '',
    baseLesson: {
      id: 1224,
      name: 'Математика 2х2 ',
      duration: 60,
      directionId: 9,
      status: 1,
      minClass: 1,
      maxClass: 1,
      minAge: 6,
      maxAge: 7
    },
    teachersName: [' Салахетдинов Руслан'],
    teacher: { name: ' Салахетдинов Руслан', bio: '', avatar: '' }
  },
  {
    id: 26075,
    name: 'Занятие 20',
    room: { id: 4, name: 'Паскаль', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T18:00:00+03:00',
    direction: 'Виртуальной реальности',
    cover:
      'https://static.tildacdn.com/tild3930-3133-4566-a332-306263303462/IMG_6000.jpg',
    description: '',
    baseLesson: {
      id: 1237,
      name: '3d-игры: программирование на Blender',
      duration: 90,
      directionId: 10,
      status: 1,
      minClass: 5,
      maxClass: 11,
      minAge: 12,
      maxAge: 18
    },
    teachersName: ['Сербаев Даниил '],
    teacher: { name: 'Сербаев Даниил ', bio: '', avatar: '' }
  },
  {
    id: 22000,
    name: 'Занятие 31',
    room: { id: 6, name: 'Чебышев', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T18:00:00+03:00',
    direction: 'Развитие способностей',
    cover:
      'https://static.tildacdn.com/tild3562-3466-4636-a132-623131396338/1.jpg',
    description: '',
    baseLesson: {
      id: 1100,
      name: 'Шахматы(продвинутые)',
      duration: 90,
      directionId: 8,
      status: 1,
      minClass: null,
      maxClass: null,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Кушнерев Олег'],
    teacher: { name: 'Кушнерев Олег', bio: '', avatar: '' }
  },
  {
    id: 27892,
    name: 'Занятие 45',
    room: { id: 19, name: 'Школа Программирования ', affiliate_id: 8 },
    branch: 'Геккон-Октябрьская',
    textStatus: 'Запись закрыта',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T19:00:00+03:00',
    direction: 'Школа программирования',
    cover: null,
    description: null,
    baseLesson: {
      id: 1301,
      name: 'Октябрьская. Информационная безопасность III',
      duration: 120,
      directionId: 16,
      status: 2,
      minClass: 7,
      maxClass: 11,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Никита Гнилозуб-Волобуев'],
    teacher: { name: 'Никита Гнилозуб-Волобуев', bio: '', avatar: '' }
  },
  {
    id: 26974,
    name: 'Занятие 22',
    room: { id: 4, name: 'Паскаль', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-06T19:30:00+03:00',
    direction: null,
    cover: null,
    description: null,
    baseLesson: {
      id: 1317,
      name: 'Индивидуальное занятие (3d-игры) Запись закрыта 19.12-25.05',
      duration: 60,
      directionId: null,
      status: 1,
      minClass: null,
      maxClass: null,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Сербаев Даниил '],
    teacher: { name: 'Сербаев Даниил ', bio: '', avatar: '' }
  },
  {
    id: 28276,
    name: 'Занятие 3',
    room: { id: 7, name: 'Сикорский', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-07T10:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3034-6134-4338-a633-356435386430/3b2262bff6304142aa101f9118f70852.jpg',
    description: '',
    baseLesson: {
      id: 1803,
      name: 'Авиамоделирование ',
      duration: 120,
      directionId: 7,
      status: 1,
      minClass: 3,
      maxClass: 7,
      minAge: 9,
      maxAge: 15
    },
    teachersName: ['Оборин Федор'],
    teacher: { name: 'Оборин Федор', bio: '', avatar: '' }
  },
  {
    id: 25308,
    name: 'Занятие 29',
    room: { id: 4, name: 'Паскаль', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-07T10:00:00+03:00',
    direction: '3D-чанк',
    cover: '',
    description: '',
    baseLesson: {
      id: 1104,
      name: 'Scratch-программирование',
      duration: 90,
      directionId: 11,
      status: 1,
      minClass: 3,
      maxClass: 4,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Погребняк Надежда '],
    teacher: { name: 'Погребняк Надежда ', bio: '', avatar: '' }
  },
  {
    id: 26167,
    name: 'Занятие 24',
    room: { id: 8, name: 'Леонардо', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-07T10:30:00+03:00',
    direction: 'Развитие способностей',
    cover: null,
    description: null,
    baseLesson: {
      id: 1269,
      name: 'Эмоциональный интеллект ',
      duration: 60,
      directionId: 8,
      status: 1,
      minClass: 1,
      maxClass: 2,
      minAge: 7,
      maxAge: 8
    },
    teachersName: [' Щёголева Анастасия'],
    teacher: { name: ' Щёголева Анастасия', bio: '', avatar: '' }
  },
  {
    id: 25343,
    name: 'Занятие 29',
    room: { id: 4, name: 'Паскаль', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-07T11:50:00+03:00',
    direction: '3D-чанк',
    cover: '',
    description: '',
    baseLesson: {
      id: 1227,
      name: 'Scratch-программирование ',
      duration: 90,
      directionId: 11,
      status: 1,
      minClass: 1,
      maxClass: 2,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Погребняк Надежда '],
    teacher: { name: 'Погребняк Надежда ', bio: '', avatar: '' }
  },
  {
    id: 26125,
    name: 'Занятие 22',
    room: { id: 5, name: 'Азимов', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-07T12:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover: null,
    description: null,
    baseLesson: {
      id: 1165,
      name: 'Инженеры-изобретатели',
      duration: null,
      directionId: 7,
      status: 1,
      minClass: 3,
      maxClass: 4,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Бувина Юлия'],
    teacher: { name: 'Бувина Юлия', bio: '', avatar: '' }
  },
  {
    id: 26147,
    name: 'Занятие 25',
    room: { id: 7, name: 'Сикорский', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-07T12:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3130-6235-4738-b430-393963393531/3.jpg',
    description: '',
    baseLesson: {
      id: 1259,
      name: 'Инженеры-изобретатели ',
      duration: 90,
      directionId: 7,
      status: 1,
      minClass: 1,
      maxClass: 2,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Козенбаева Юлиана'],
    teacher: { name: 'Козенбаева Юлиана', bio: '', avatar: '' }
  },
  {
    id: 26107,
    name: 'Занятие 26',
    room: { id: 6, name: 'Чебышев', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-07T12:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3034-6134-4338-a633-356435386430/3b2262bff6304142aa101f9118f70852.jpg',
    description: '',
    baseLesson: {
      id: 1115,
      name: 'Авиамоделирование (начало)',
      duration: 120,
      directionId: 7,
      status: 1,
      minClass: 3,
      maxClass: 4,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Оборин Федор'],
    teacher: { name: 'Оборин Федор', bio: '', avatar: '' }
  },
  {
    id: 26187,
    name: 'Занятие 29',
    room: { id: 4, name: 'Паскаль', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-07T13:20:00+03:00',
    direction: 'Чанк Lego-A',
    cover:
      'https://static.tildacdn.com/tild6437-6335-4434-b838-353937633261/4.jpg',
    description: '',
    baseLesson: {
      id: 1105,
      name: 'Lego WeDo',
      duration: 90,
      directionId: 4,
      status: 1,
      minClass: 1,
      maxClass: 2,
      minAge: 6,
      maxAge: 8
    },
    teachersName: ['Бабешкина Елена'],
    teacher: { name: 'Бабешкина Елена', bio: '', avatar: '' }
  },
  {
    id: 26245,
    name: 'Занятие 29',
    room: { id: 7, name: 'Сикорский', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-07T14:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3034-6134-4338-a633-356435386430/3b2262bff6304142aa101f9118f70852.jpg',
    description: '',
    baseLesson: {
      id: 1235,
      name: 'Авиамоделирование',
      duration: 120,
      directionId: 7,
      status: 1,
      minClass: 5,
      maxClass: 10,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Оборин Федор'],
    teacher: { name: 'Оборин Федор', bio: '', avatar: '' }
  },
  {
    id: 26589,
    name: 'Занятие 13',
    room: { id: 13, name: 'Столярная мастерская', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-07T14:00:00+03:00',
    direction: 'Развитие способностей',
    cover: null,
    description: null,
    baseLesson: {
      id: 1503,
      name: 'Шахматы (начинающие) 2019',
      duration: 60,
      directionId: 8,
      status: 1,
      minClass: 0,
      maxClass: 3,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Кушнерев Олег'],
    teacher: { name: 'Кушнерев Олег', bio: '', avatar: '' }
  },
  {
    id: 26207,
    name: 'Занятие 29',
    room: { id: 5, name: 'Азимов', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-07T14:15:00+03:00',
    direction: 'Электроника',
    cover: null,
    description: null,
    baseLesson: {
      id: 1166,
      name: 'Электроника  (Начало)',
      duration: 90,
      directionId: 13,
      status: 1,
      minClass: 3,
      maxClass: 4,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Рогатых Денис'],
    teacher: { name: 'Рогатых Денис', bio: '', avatar: '' }
  },
  {
    id: 26265,
    name: 'Занятие 29',
    room: { id: 4, name: 'Паскаль', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-07T15:00:00+03:00',
    direction: 'Чанк Lego-A',
    cover:
      'https://static.tildacdn.com/tild6437-6335-4434-b838-353937633261/4.jpg',
    description: '',
    baseLesson: {
      id: 1106,
      name: 'Lego WeDo (Продолжение)',
      duration: 90,
      directionId: 4,
      status: 1,
      minClass: 1,
      maxClass: 2,
      minAge: 6,
      maxAge: 8
    },
    teachersName: ['Бабешкина Елена'],
    teacher: { name: 'Бабешкина Елена', bio: '', avatar: '' }
  },
  {
    id: 27855,
    name: 'Занятие 48',
    room: { id: 19, name: 'Школа Программирования ', affiliate_id: 8 },
    branch: 'Геккон-Октябрьская',
    textStatus: 'Запись закрыта',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-07T15:35:00+03:00',
    direction: 'Школа программирования',
    cover: null,
    description: null,
    baseLesson: {
      id: 1299,
      name: 'Октябрьская. Информационная безопасность',
      duration: 120,
      directionId: 16,
      status: 2,
      minClass: 7,
      maxClass: 11,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Никита Гнилозуб-Волобуев'],
    teacher: { name: 'Никита Гнилозуб-Волобуев', bio: '', avatar: '' }
  },
  {
    id: 26627,
    name: 'Занятие 13',
    room: { id: 13, name: 'Столярная мастерская', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-07T16:00:00+03:00',
    direction: null,
    cover: null,
    description: null,
    baseLesson: {
      id: 1505,
      name: 'Квадрокоптеры и 3D-печать 2019',
      duration: 120,
      directionId: null,
      status: 1,
      minClass: 3,
      maxClass: 4,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Соловьев Дмитрий'],
    teacher: { name: 'Соловьев Дмитрий', bio: '', avatar: '' }
  },
  {
    id: 27643,
    name: 'Занятие 18',
    room: { id: 4, name: 'Паскаль', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-07T16:00:00+03:00',
    direction: 'Школа программирования',
    cover: null,
    description: null,
    baseLesson: {
      id: 1705,
      name: 'Питон для продолжающих 2019/1',
      duration: 90,
      directionId: 16,
      status: 1,
      minClass: 7,
      maxClass: 11,
      minAge: null,
      maxAge: null
    },
    teachersName: [' Ростислав Бородин'],
    teacher: {
      name: ' Ростислав Бородин',
      bio: '',
      avatar: 'http://class.roctbb.net'
    }
  },
  {
    id: 26285,
    name: 'Занятие 29',
    room: { id: 4, name: 'Паскаль', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-07T16:30:00+03:00',
    direction: 'Чанк Lego-A',
    cover: '',
    description: '',
    baseLesson: {
      id: 1107,
      name: 'Lego Простые механизмы',
      duration: 60,
      directionId: 4,
      status: 1,
      minClass: null,
      maxClass: null,
      minAge: 4,
      maxAge: 7
    },
    teachersName: ['Бабешкина Елена'],
    teacher: { name: 'Бабешкина Елена', bio: '', avatar: '' }
  },
  {
    id: 26663,
    name: 'Занятие 13',
    room: { id: 13, name: 'Столярная мастерская', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-07T18:00:00+03:00',
    direction: null,
    cover: null,
    description: null,
    baseLesson: {
      id: 1507,
      name: '3D-графика и печать 2019',
      duration: 90,
      directionId: null,
      status: 1,
      minClass: 3,
      maxClass: 4,
      minAge: null,
      maxAge: null
    },
    teachersName: [' Сахибгареев Булат'],
    teacher: { name: ' Сахибгареев Булат', bio: '', avatar: '' }
  },
  {
    id: 27718,
    name: 'Занятие 18',
    room: { id: 19, name: 'Школа Программирования ', affiliate_id: 8 },
    branch: 'Геккон-Октябрьская',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-07T18:00:00+03:00',
    direction: 'Школа программирования',
    cover: null,
    description: null,
    baseLesson: {
      id: 1708,
      name: 'Frontend&Backend 2019/1',
      duration: 90,
      directionId: 16,
      status: 1,
      minClass: 7,
      maxClass: 11,
      minAge: null,
      maxAge: null
    },
    teachersName: [' Ростислав Бородин'],
    teacher: {
      name: ' Ростислав Бородин',
      bio: '',
      avatar: 'http://class.roctbb.net'
    }
  },
  {
    id: 27893,
    name: 'Занятие 46',
    room: { id: 19, name: 'Школа Программирования ', affiliate_id: 8 },
    branch: 'Геккон-Октябрьская',
    textStatus: 'Запись закрыта',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-07T19:00:00+03:00',
    direction: 'Школа программирования',
    cover: null,
    description: null,
    baseLesson: {
      id: 1301,
      name: 'Октябрьская. Информационная безопасность III',
      duration: 120,
      directionId: 16,
      status: 2,
      minClass: 7,
      maxClass: 11,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Никита Гнилозуб-Волобуев'],
    teacher: { name: 'Никита Гнилозуб-Волобуев', bio: '', avatar: '' }
  },
  {
    id: 28229,
    name: 'Занятие 1',
    room: { id: 7, name: 'Сикорский', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-08T10:00:00+03:00',
    direction: null,
    cover: null,
    description: null,
    baseLesson: {
      id: 1780,
      name: 'ИНТЕНСИВ МАШИНА ГОЛДБЕРГА 8.04-12.04',
      duration: 180,
      directionId: null,
      status: 1,
      minClass: 1,
      maxClass: 2,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Козенбаева Юлиана'],
    teacher: { name: 'Козенбаева Юлиана', bio: '', avatar: '' }
  },
  {
    id: 28234,
    name: 'Занятие 1',
    room: { id: 5, name: 'Азимов', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-08T10:00:00+03:00',
    direction: null,
    cover: null,
    description: null,
    baseLesson: {
      id: 1781,
      name: 'ИНТЕНСИВ Стань пилотом КВАДРОКОПТЕРА 8.04.-12.04',
      duration: 180,
      directionId: null,
      status: 1,
      minClass: 3,
      maxClass: 7,
      minAge: 9,
      maxAge: 14
    },
    teachersName: ['Оборин Федор'],
    teacher: { name: 'Оборин Федор', bio: '', avatar: '' }
  },
  {
    id: 28239,
    name: 'Занятие 1',
    room: { id: 4, name: 'Паскаль', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-08T13:05:00+03:00',
    direction: null,
    cover: null,
    description: null,
    baseLesson: {
      id: 1782,
      name: 'ИНТЕНСИВ Конструируем ТЕПЛОВОЗ 8.04.-12.04.',
      duration: 180,
      directionId: null,
      status: 1,
      minClass: 3,
      maxClass: 4,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Ситдикова Камилла'],
    teacher: { name: 'Ситдикова Камилла', bio: '', avatar: '' }
  },
  {
    id: 25370,
    name: 'Занятие 30',
    room: { id: 7, name: 'Сикорский', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-08T15:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3130-6235-4738-b430-393963393531/3.jpg',
    description: '',
    baseLesson: {
      id: 1133,
      name: 'Инженеры-изобретатели ',
      duration: 90,
      directionId: 7,
      status: 1,
      minClass: 1,
      maxClass: 2,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Гришина Виктория '],
    teacher: { name: 'Гришина Виктория ', bio: '', avatar: '' }
  },
  {
    id: 28488,
    name: 'Занятие 1',
    room: { id: 4, name: 'Паскаль', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-08T15:00:00+03:00',
    direction: null,
    cover: null,
    description: null,
    baseLesson: {
      id: 1886,
      name: 'Индивидуальное занятие Scratch-программирование 8.04',
      duration: 120,
      directionId: null,
      status: 1,
      minClass: 2,
      maxClass: 2,
      minAge: 8,
      maxAge: 8
    },
    teachersName: ['Погребняк Надежда '],
    teacher: { name: 'Погребняк Надежда ', bio: '', avatar: '' }
  },
  {
    id: 26994,
    name: 'Занятие 21',
    room: { id: 13, name: 'Столярная мастерская', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Запись закрыта',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-08T15:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover: null,
    description: null,
    baseLesson: {
      id: 1419,
      name: 'Индивидуальное занятие Инженеры-изобретатели 1-2 с 19.11 по 20.05',
      duration: 90,
      directionId: 7,
      status: 2,
      minClass: 1,
      maxClass: 2,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Ярыгина Дарья '],
    teacher: {
      name: 'Ярыгина Дарья ',
      bio:
        'Инженер. Закончила МГТУ им. Баумана в 2018 году. Опыт преподавания с 2015-го года.',
      avatar:
        'https://static.tildacdn.com/tild3239-6561-4537-a164-613236623366/IMG_0070_1000px.JPG'
    }
  },
  {
    id: 25390,
    name: 'Занятие 28',
    room: { id: 8, name: 'Леонардо', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-08T16:30:00+03:00',
    direction: 'Развитие способностей',
    cover:
      'https://static.tildacdn.com/tild3562-3466-4636-a132-623131396338/1.jpg',
    description: '',
    baseLesson: {
      id: 1018,
      name: 'Шахматы (продолжающие)',
      duration: 60,
      directionId: 8,
      status: 1,
      minClass: null,
      maxClass: null,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Уколов Александр'],
    teacher: { name: 'Уколов Александр', bio: '', avatar: '' }
  },
  {
    id: 25410,
    name: 'Занятие 30',
    room: { id: 7, name: 'Сикорский', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-08T17:00:00+03:00',
    direction: 'Чанк Lego-A',
    cover: '',
    description: '',
    baseLesson: {
      id: 1015,
      name: 'Lego Простые механизмы',
      duration: 60,
      directionId: 4,
      status: 1,
      minClass: 0,
      maxClass: null,
      minAge: 5,
      maxAge: 6
    },
    teachersName: ['Ситдикова Камилла'],
    teacher: { name: 'Ситдикова Камилла', bio: '', avatar: '' }
  },
  {
    id: 26690,
    name: 'Занятие 29',
    room: { id: 5, name: 'Азимов', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-08T18:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3130-6235-4738-b430-393963393531/3.jpg',
    description: '',
    baseLesson: {
      id: 1134,
      name: 'Инженеры-изобретатели Проектная',
      duration: 120,
      directionId: 7,
      status: 1,
      minClass: 5,
      maxClass: 10,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Суетин Никита ', 'Рудов Дмитрий '],
    teacher: { name: 'Суетин Никита ', bio: '', avatar: '' }
  },
  {
    id: 26806,
    name: 'Занятие 29',
    room: { id: 7, name: 'Сикорский', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-08T18:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3130-6235-4738-b430-393963393531/3.jpg',
    description: '',
    baseLesson: {
      id: 1196,
      name: 'Инженеры-изобретатели ',
      duration: 120,
      directionId: 7,
      status: 1,
      minClass: 3,
      maxClass: 4,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Ситдикова Камилла'],
    teacher: { name: 'Ситдикова Камилла', bio: '', avatar: '' }
  },
  {
    id: 28230,
    name: 'Занятие 2',
    room: { id: 7, name: 'Сикорский', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-09T10:00:00+03:00',
    direction: null,
    cover: null,
    description: null,
    baseLesson: {
      id: 1780,
      name: 'ИНТЕНСИВ МАШИНА ГОЛДБЕРГА 8.04-12.04',
      duration: 180,
      directionId: null,
      status: 1,
      minClass: 1,
      maxClass: 2,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Козенбаева Юлиана'],
    teacher: { name: 'Козенбаева Юлиана', bio: '', avatar: '' }
  },
  {
    id: 28235,
    name: 'Занятие 2',
    room: { id: 5, name: 'Азимов', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-09T10:00:00+03:00',
    direction: null,
    cover: null,
    description: null,
    baseLesson: {
      id: 1781,
      name: 'ИНТЕНСИВ Стань пилотом КВАДРОКОПТЕРА 8.04.-12.04',
      duration: 180,
      directionId: null,
      status: 1,
      minClass: 3,
      maxClass: 7,
      minAge: 9,
      maxAge: 14
    },
    teachersName: ['Оборин Федор'],
    teacher: { name: 'Оборин Федор', bio: '', avatar: '' }
  },
  {
    id: 27550,
    name: 'Занятие 15',
    room: { id: 7, name: 'Сикорский', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-09T14:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover: null,
    description: null,
    baseLesson: {
      id: 1345,
      name: 'Инженеры-изобретатели (начало)',
      duration: 90,
      directionId: 7,
      status: 1,
      minClass: 1,
      maxClass: 2,
      minAge: 7,
      maxAge: 8
    },
    teachersName: ['Гришина Виктория '],
    teacher: { name: 'Гришина Виктория ', bio: '', avatar: '' }
  },
  {
    id: 25430,
    name: 'Занятие 22',
    room: { id: 4, name: 'Паскаль', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Запись закрыта',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-09T15:00:00+03:00',
    direction: 'Виртуальной реальности',
    cover:
      'https://static.tildacdn.com/tild3930-3133-4566-a332-306263303462/IMG_6000.jpg',
    description: '',
    baseLesson: {
      id: 1030,
      name: 'Моды майнкрафта',
      duration: 90,
      directionId: 10,
      status: 2,
      minClass: 1,
      maxClass: 4,
      minAge: 7,
      maxAge: 12
    },
    teachersName: ['Сербаев Даниил '],
    teacher: { name: 'Сербаев Даниил ', bio: '', avatar: '' }
  },
  {
    id: 25453,
    name: 'Занятие 28',
    room: { id: 7, name: 'Сикорский', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-09T16:00:00+03:00',
    direction: 'Чанк Lego-A',
    cover:
      'https://static.tildacdn.com/tild6437-6335-4434-b838-353937633261/4.jpg',
    description: '',
    baseLesson: {
      id: 1140,
      name: 'Lego WeDo (начало)',
      duration: 90,
      directionId: 4,
      status: 1,
      minClass: 1,
      maxClass: 2,
      minAge: 6,
      maxAge: 8
    },
    teachersName: ['Гришина Виктория '],
    teacher: { name: 'Гришина Виктория ', bio: '', avatar: '' }
  },
  {
    id: 20083,
    name: 'Занятие 20',
    room: { id: 5, name: 'Азимов', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-09T17:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3034-6134-4338-a633-356435386430/3b2262bff6304142aa101f9118f70852.jpg',
    description: '',
    baseLesson: {
      id: 1032,
      name: 'Авиамоделирование (Проектная группа)',
      duration: 120,
      directionId: 7,
      status: 1,
      minClass: 3,
      maxClass: 7,
      minAge: 8,
      maxAge: 11
    },
    teachersName: [' Фёдоров Александр'],
    teacher: { name: ' Фёдоров Александр', bio: '', avatar: '' }
  },
  {
    id: 25477,
    name: 'Занятие 25',
    room: { id: 8, name: 'Леонардо', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-09T19:00:00+03:00',
    direction: 'Развитие способностей',
    cover: null,
    description: null,
    baseLesson: {
      id: 1268,
      name: 'Эмоциональный интеллект ',
      duration: 60,
      directionId: 8,
      status: 1,
      minClass: 0,
      maxClass: 0,
      minAge: 5,
      maxAge: 6
    },
    teachersName: [' Щёголева Анастасия'],
    teacher: { name: ' Щёголева Анастасия', bio: '', avatar: '' }
  },
  {
    id: 28231,
    name: 'Занятие 3',
    room: { id: 7, name: 'Сикорский', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-10T10:00:00+03:00',
    direction: null,
    cover: null,
    description: null,
    baseLesson: {
      id: 1780,
      name: 'ИНТЕНСИВ МАШИНА ГОЛДБЕРГА 8.04-12.04',
      duration: 180,
      directionId: null,
      status: 1,
      minClass: 1,
      maxClass: 2,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Козенбаева Юлиана'],
    teacher: { name: 'Козенбаева Юлиана', bio: '', avatar: '' }
  },
  {
    id: 28236,
    name: 'Занятие 3',
    room: { id: 5, name: 'Азимов', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-10T10:00:00+03:00',
    direction: null,
    cover: null,
    description: null,
    baseLesson: {
      id: 1781,
      name: 'ИНТЕНСИВ Стань пилотом КВАДРОКОПТЕРА 8.04.-12.04',
      duration: 180,
      directionId: null,
      status: 1,
      minClass: 3,
      maxClass: 7,
      minAge: 9,
      maxAge: 14
    },
    teachersName: ['Оборин Федор'],
    teacher: { name: 'Оборин Федор', bio: '', avatar: '' }
  },
  {
    id: 25498,
    name: 'Занятие 31',
    room: { id: 4, name: 'Паскаль', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-10T14:00:00+03:00',
    direction: '3D-чанк',
    cover: '',
    description: '',
    baseLesson: {
      id: 1142,
      name: 'Scratch-программирование',
      duration: 90,
      directionId: 11,
      status: 1,
      minClass: 1,
      maxClass: 1,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Гришина Виктория '],
    teacher: { name: 'Гришина Виктория ', bio: '', avatar: '' }
  },
  {
    id: 28465,
    name: 'Занятие 1',
    room: { id: 4, name: 'Паскаль', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 1,
    textType: 'Мастер-класс',
    startDate: '2019-04-10T16:00:00+03:00',
    direction: 'Мастер-класс',
    cover:
      'https://static.tildacdn.com/tild3332-3231-4434-b766-393938633962/_7.jpg',
    description:
      'Дети соберут действующую копию пистолета ТТ из фанерных деталей и узнают о легендарном оружии Советской армии!\r\n\r\nНа мастер-классе ребята:\r\nизучат историю самого массового оружия Советской армии\r\nразберутся с устройством модели\r\nсамостоятельно соберут пистолеты\r\nпримут участие в соревновании по стрельбе\r\n\r\nСобранные пистолеты ребята заберут с собой и дома смогут оттачивать навыки по стрельбе!',
    baseLesson: {
      id: 1870,
      name: 'МК Пистолет ТТ 10.04',
      duration: 60,
      directionId: 17,
      status: 1,
      minClass: 1,
      maxClass: 4,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Гришина Виктория '],
    teacher: { name: 'Гришина Виктория ', bio: '', avatar: '' }
  },
  {
    id: 25520,
    name: 'Занятие 30',
    room: { id: 8, name: 'Леонардо', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-10T16:00:00+03:00',
    direction: 'Развитие способностей',
    cover: null,
    description: null,
    baseLesson: {
      id: 1184,
      name: 'Развитие памяти и скорочтение',
      duration: 90,
      directionId: 8,
      status: 1,
      minClass: 3,
      maxClass: 4,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Ахмадеева Диана'],
    teacher: { name: 'Ахмадеева Диана', bio: '', avatar: '' }
  },
  {
    id: 28464,
    name: 'Занятие 1',
    room: { id: 4, name: 'Паскаль', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 1,
    textType: 'Мастер-класс',
    startDate: '2019-04-10T17:00:00+03:00',
    direction: 'Мастер-класс',
    cover:
      'https://static.tildacdn.com/tild3961-3831-4331-a366-393564383736/__2017-12-05__160515.png',
    description:
      'В основе конструкции — робот, которого дети собирают из деталей, изготовленных лазером. В его голове — светодиоды, благодаря чему он светится.\r\n\r\nРебята на мастер классе:\r\nпознакомятся с азами электроники\r\nнаучаться работать с паяльником и другими инструментами\r\nузнают, что такое светодиод и резистор\r\nРебята самостоятельно соберут настоящую роболампу, которую можно использовать как лампу на рабочем столе или же как ночник. \r\nЗаписаться на мастер-класс ',
    baseLesson: {
      id: 1869,
      name: 'МК Роболампа 10.04',
      duration: 60,
      directionId: 17,
      status: 1,
      minClass: 1,
      maxClass: 10,
      minAge: 7,
      maxAge: 17
    },
    teachersName: ['Изотова Анастасия'],
    teacher: { name: 'Изотова Анастасия', bio: '', avatar: '' }
  },
  {
    id: 21065,
    name: 'Занятие 32',
    room: { id: 5, name: 'Азимов', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-10T17:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3130-6235-4738-b430-393963393531/3.jpg',
    description: '',
    baseLesson: {
      id: 1074,
      name: 'Инженеры-изобретатели ',
      duration: 120,
      directionId: 7,
      status: 1,
      minClass: 3,
      maxClass: 4,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Ситдикова Камилла'],
    teacher: { name: 'Ситдикова Камилла', bio: '', avatar: '' }
  },
  {
    id: 28463,
    name: 'Занятие 1',
    room: { id: 5, name: 'Азимов', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 1,
    textType: 'Мастер-класс',
    startDate: '2019-04-10T18:00:00+03:00',
    direction: 'Мастер-класс',
    cover:
      'https://static.tildacdn.com/tild3935-6563-4832-b164-373065326235/photo.png',
    description:
      'Соберите свинью-копилку, копирующую легендарного моба из Майнкрафта. Чтобы достать монеты, не придётся ломать копилку, достаточно дёрнуть её за хвост и открыть, как коробку. А поскольку мы инженеры, наша свинка будет мигать светодиодом от каждой брошенной монетки\r\n',
    baseLesson: {
      id: 1868,
      name: 'МК Свинья-копилка из Майнкрафта 10.04',
      duration: 60,
      directionId: 17,
      status: 1,
      minClass: 1,
      maxClass: 9,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Гришина Виктория '],
    teacher: { name: 'Гришина Виктория ', bio: '', avatar: '' }
  },
  {
    id: 25541,
    name: 'Занятие 25',
    room: { id: 4, name: 'Паскаль', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-10T18:00:00+03:00',
    direction: 'Чанк Lego-A',
    cover:
      'https://static.tildacdn.com/tild6437-6335-4434-b838-353937633261/4.jpg',
    description: '',
    baseLesson: {
      id: 1039,
      name: 'Lego WeDo (начало)',
      duration: 90,
      directionId: 4,
      status: 1,
      minClass: 1,
      maxClass: 2,
      minAge: 6,
      maxAge: 8
    },
    teachersName: ['Козенбаева Юлиана'],
    teacher: { name: 'Козенбаева Юлиана', bio: '', avatar: '' }
  },
  {
    id: 25559,
    name: 'Занятие 30',
    room: { id: 7, name: 'Сикорский', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-10T18:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3034-6134-4338-a633-356435386430/3b2262bff6304142aa101f9118f70852.jpg',
    description: '',
    baseLesson: {
      id: 1143,
      name: 'Авиамоделирование(начало)',
      duration: 120,
      directionId: 7,
      status: 1,
      minClass: 3,
      maxClass: 4,
      minAge: 8,
      maxAge: 11
    },
    teachersName: ['Соловьев Дмитрий'],
    teacher: { name: 'Соловьев Дмитрий', bio: '', avatar: '' }
  },
  {
    id: 26366,
    name: 'Занятие 14',
    room: { id: 13, name: 'Столярная мастерская', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-10T18:00:00+03:00',
    direction: null,
    cover: null,
    description: null,
    baseLesson: {
      id: 1492,
      name: 'Квадрокоптеры и 3D-печать 2019',
      duration: 120,
      directionId: null,
      status: 1,
      minClass: 5,
      maxClass: 10,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Оборин Федор'],
    teacher: { name: 'Оборин Федор', bio: '', avatar: '' }
  },
  {
    id: 28462,
    name: 'Занятие 1',
    room: { id: 13, name: 'Столярная мастерская', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 1,
    textType: 'Мастер-класс',
    startDate: '2019-04-10T18:30:00+03:00',
    direction: 'Мастер-класс',
    cover:
      'https://static.tildacdn.com/tild6165-3533-4739-b564-356533303431/photo.png',
    description:
      'На этом мастер классе дети почувствуют себя настоящими программистами и познакомятся с целым миром Scratch-программирования!\r\n\r\nРебята на мастер классе:\r\nнаучатся основам программирования на Scratch\r\nузнают, как пользоваться элементарными командами и алгоритмами\r\nнапишут свои первые программы\r\nГеймифицированная структура мастер-класса сделает его не только познавательным, но и интересным: после первичной подготовки участники отправятся на экскурсию по Марсианской базе, где главным инструментом в их исследованиях послужат полученные ранее знания!',
    baseLesson: {
      id: 1867,
      name: 'МК Scratch-программирование 10.04 ',
      duration: 60,
      directionId: 17,
      status: 1,
      minClass: 1,
      maxClass: 4,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Погребняк Надежда '],
    teacher: { name: 'Погребняк Надежда ', bio: '', avatar: '' }
  },
  {
    id: 25578,
    name: 'Занятие 29',
    room: { id: 8, name: 'Леонардо', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-10T18:30:00+03:00',
    direction: null,
    cover: null,
    description: null,
    baseLesson: {
      id: 1185,
      name: 'Развитие памяти и скорочтение',
      duration: 90,
      directionId: null,
      status: 1,
      minClass: 5,
      maxClass: 7,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Ахмадеева Диана'],
    teacher: { name: 'Ахмадеева Диана', bio: '', avatar: '' }
  },
  {
    id: 28232,
    name: 'Занятие 4',
    room: { id: 7, name: 'Сикорский', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-11T10:00:00+03:00',
    direction: null,
    cover: null,
    description: null,
    baseLesson: {
      id: 1780,
      name: 'ИНТЕНСИВ МАШИНА ГОЛДБЕРГА 8.04-12.04',
      duration: 180,
      directionId: null,
      status: 1,
      minClass: 1,
      maxClass: 2,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Козенбаева Юлиана'],
    teacher: { name: 'Козенбаева Юлиана', bio: '', avatar: '' }
  },
  {
    id: 28237,
    name: 'Занятие 4',
    room: { id: 5, name: 'Азимов', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-11T10:00:00+03:00',
    direction: null,
    cover: null,
    description: null,
    baseLesson: {
      id: 1781,
      name: 'ИНТЕНСИВ Стань пилотом КВАДРОКОПТЕРА 8.04.-12.04',
      duration: 180,
      directionId: null,
      status: 1,
      minClass: 3,
      maxClass: 7,
      minAge: 9,
      maxAge: 14
    },
    teachersName: ['Оборин Федор'],
    teacher: { name: 'Оборин Федор', bio: '', avatar: '' }
  },
  {
    id: 25598,
    name: 'Занятие 28',
    room: { id: 8, name: 'Леонардо', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-11T12:00:00+03:00',
    direction: 'Физико-математический Чанк',
    cover:
      'https://static.tildacdn.com/tild6164-6237-4531-b839-333237376135/5.jpg',
    description: '',
    baseLesson: {
      id: 1151,
      name: 'Математика 2х2',
      duration: 60,
      directionId: 9,
      status: 1,
      minClass: 0,
      maxClass: 0,
      minAge: 5,
      maxAge: 6
    },
    teachersName: [' Салахетдинов Руслан'],
    teacher: { name: ' Салахетдинов Руслан', bio: '', avatar: '' }
  },
  {
    id: 25642,
    name: 'Занятие 47',
    room: { id: 4, name: 'Паскаль', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-11T13:30:00+03:00',
    direction: 'Чанк Lego-B',
    cover: null,
    description: null,
    baseLesson: {
      id: 1279,
      name: 'Lego WeDo',
      duration: 90,
      directionId: 5,
      status: 1,
      minClass: 0,
      maxClass: 2,
      minAge: 6,
      maxAge: 8
    },
    teachersName: ['Козенбаева Юлиана'],
    teacher: { name: 'Козенбаева Юлиана', bio: '', avatar: '' }
  },
  {
    id: 25664,
    name: 'Занятие 30',
    room: { id: 8, name: 'Леонардо', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-11T15:00:00+03:00',
    direction: null,
    cover: null,
    description: null,
    baseLesson: {
      id: 1186,
      name: 'Арт-терапия',
      duration: 90,
      directionId: null,
      status: 1,
      minClass: 1,
      maxClass: 2,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Ахмадеева Диана'],
    teacher: { name: 'Ахмадеева Диана', bio: '', avatar: '' }
  },
  {
    id: 21209,
    name: 'Занятие 32',
    room: { id: 5, name: 'Азимов', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-11T15:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3130-6235-4738-b430-393963393531/3.jpg',
    description: '',
    baseLesson: {
      id: 1078,
      name: 'Инженеры-изобретатели',
      duration: 90,
      directionId: 7,
      status: 1,
      minClass: 1,
      maxClass: 2,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Гришина Виктория '],
    teacher: { name: 'Гришина Виктория ', bio: '', avatar: '' }
  },
  {
    id: 25686,
    name: 'Занятие 29',
    room: { id: 8, name: 'Леонардо', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-11T17:00:00+03:00',
    direction: null,
    cover: null,
    description: null,
    baseLesson: {
      id: 1187,
      name: 'Арт-терапия',
      duration: 60,
      directionId: null,
      status: 1,
      minClass: 0,
      maxClass: 1,
      minAge: 5,
      maxAge: 7
    },
    teachersName: ['Ахмадеева Диана'],
    teacher: { name: 'Ахмадеева Диана', bio: '', avatar: '' }
  },
  {
    id: 26408,
    name: 'Занятие 14',
    room: { id: 13, name: 'Столярная мастерская', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-11T18:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3130-6235-4738-b430-393963393531/3.jpg',
    description: '',
    baseLesson: {
      id: 1494,
      name: 'Инженеры-изобретатели (3-4кл.) 2019',
      duration: 120,
      directionId: 7,
      status: 1,
      minClass: 3,
      maxClass: 4,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Ситдикова Камилла'],
    teacher: { name: 'Ситдикова Камилла', bio: '', avatar: '' }
  },
  {
    id: 27719,
    name: 'Занятие 19',
    room: { id: 19, name: 'Школа Программирования ', affiliate_id: 8 },
    branch: 'Геккон-Октябрьская',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-11T18:00:00+03:00',
    direction: 'Школа программирования',
    cover: null,
    description: null,
    baseLesson: {
      id: 1708,
      name: 'Frontend&Backend 2019/1',
      duration: 90,
      directionId: 16,
      status: 1,
      minClass: 7,
      maxClass: 11,
      minAge: null,
      maxAge: null
    },
    teachersName: [' Ростислав Бородин'],
    teacher: {
      name: ' Ростислав Бородин',
      bio: '',
      avatar: 'http://class.roctbb.net'
    }
  },
  {
    id: 25708,
    name: 'Занятие 30',
    room: { id: 5, name: 'Азимов', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-11T18:00:00+03:00',
    direction: 'Чанк Инженерное проектирование',
    cover:
      'https://static.tildacdn.com/tild3130-6235-4738-b430-393963393531/3.jpg',
    description: '',
    baseLesson: {
      id: 1148,
      name: 'Инженеры-изобретатели',
      duration: 120,
      directionId: 7,
      status: 1,
      minClass: 5,
      maxClass: 10,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Стегура Никита'],
    teacher: { name: 'Стегура Никита', bio: '', avatar: '' }
  },
  {
    id: 25729,
    name: 'Занятие 30',
    room: { id: 8, name: 'Леонардо', affiliate_id: 1 },
    branch: 'Геккон - основной',
    textStatus: 'Идёт запись',
    type: 0,
    textType: 'Кружок',
    startDate: '2019-04-11T18:30:00+03:00',
    direction: null,
    cover: null,
    description: null,
    baseLesson: {
      id: 1188,
      name: 'Арт-терапия',
      duration: 90,
      directionId: null,
      status: 1,
      minClass: 3,
      maxClass: 4,
      minAge: null,
      maxAge: null
    },
    teachersName: ['Ахмадеева Диана'],
    teacher: { name: 'Ахмадеева Диана', bio: '', avatar: '' }
  }
]

export default schedule
